In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_path = "ACSST1Y2024.S1902-2026-05-08T012308.csv"

df = pd.read_csv(file_path)

df.head(20)

,Label (Grouping),Massachusetts!!Number!!Estimate,Massachusetts!!Number!!Margin of Error,Massachusetts!!Percent Distribution!!Estimate,Massachusetts!!Percent Distribution!!Margin of Error,Massachusetts!!Mean income (dollars)!!Estimate,Massachusetts!!Mean income (dollars)!!Margin of Error,"Boston city, Massachusetts!!Number!!Estimate","Boston city, Massachusetts!!Number!!Margin of Error","Boston city, Massachusetts!!Percent Distribution!!Estimate","Boston city, Massachusetts!!Percent Distribution!!Margin of Error","Boston city, Massachusetts!!Mean income (dollars)!!Estimate","Boston city, Massachusetts!!Mean income (dollars)!!Margin of Error"
0,HOUSEHOLD INCOME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,All households,"2,829,804","9,140","2,829,804","9,140","144,312","1,304","294,977","3,333","294,977","3,333","138,724","5,206"
2,With earnings,"2,226,456","11,252",78.70%,0.3,"149,436","1,513","238,679","5,436",80.90%,1.4,"147,632","4,750"
3,With wages or salary income,"2,160,543","12,511",76.30%,0.4,"146,494","1,441","234,329","5,448",79.40%,1.5,"145,324","4,915"
4,With self-employment income,"310,653","9,386",11.00%,0.3,"52,170","3,270","27,637","2,832",9.40%,1,"42,809","12,737"
5,"With interest, dividends, or net renta...","725,865","13,198",25.70%,0.5,"32,557","2,251","71,037","4,722",24.10%,1.5,"36,528","10,365"
6,With Social Security income,"872,672","10,854",30.80%,0.4,"25,232",325,"63,049","3,320",21.40%,1.1,"21,709","1,387"
7,With Supplemental Security Income (SSI),"151,041","6,430",5.30%,0.2,"10,918",348,"20,624","3,177",7.00%,1.1,"10,561",768
8,With cash public assistance income or ...,"454,353","10,564",16.10%,0.4,(X),(X),"65,125","3,882",22.10%,1.3,(X),(X)
9,With cash public assistance,"95,822","5,743",3.40%,0.2,"4,294",300,"12,078","2,060",4.10%,0.7,"4,057",761
10,With retirement income,"669,715","11,545",23.70%,0.4,"36,493","1,258","42,204","3,351",14.30%,1.1,"29,753","2,896"
11,With other types of income,"219,633","7,679",7.80%,0.3,"15,991",767,"15,894","2,481",5.40%,0.8,"12,437","2,131"
12,FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,All families,"1,761,366","13,364","1,761,366","13,364","174,000","1,658","130,183","5,138","130,183","5,138","165,069","10,433"
14,No workers,"224,175","8,094",12.70%,0.5,"87,875","4,196","16,263","1,962",12.50%,1.6,"66,425","22,918"
15,1 worker,"471,776","10,336",26.80%,0.6,"127,573","4,182","39,338","4,118",30.20%,2.8,"124,452","27,512"
16,"2 workers, both spouses worked","581,201","10,291",33.00%,0.5,"230,694","3,605","38,018","3,482",29.20%,2.3,"258,072","17,673"
17,"2 workers, other","206,666","8,709",11.70%,0.5,"139,954","4,948","19,723","2,608",15.20%,2,"132,882","16,802"
18,"3 or more workers, both spouses worked","198,427","7,923",11.30%,0.4,"250,850","6,348","9,461","1,810",7.30%,1.3,"205,289","29,582"
19,"3 or more workers, other","79,121","5,818",4.50%,0.3,"174,588","9,002","7,380","1,882",5.70%,1.4,"154,300","19,339"

In [4]:
for col in df.columns:
    print(col)

Label (Grouping)
Massachusetts!!Number!!Estimate
Massachusetts!!Number!!Margin of Error
Massachusetts!!Percent Distribution!!Estimate
Massachusetts!!Percent Distribution!!Margin of Error
Massachusetts!!Mean income (dollars)!!Estimate
Massachusetts!!Mean income (dollars)!!Margin of Error
Boston city, Massachusetts!!Number!!Estimate
Boston city, Massachusetts!!Number!!Margin of Error
Boston city, Massachusetts!!Percent Distribution!!Estimate
Boston city, Massachusetts!!Percent Distribution!!Margin of Error
Boston city, Massachusetts!!Mean income (dollars)!!Estimate
Boston city, Massachusetts!!Mean income (dollars)!!Margin of Error

In [5]:
df = df.rename(columns={
    "Label (Grouping)": "race",
    "Boston city, Massachusetts!!Number!!Estimate": "number",
    "Boston city, Massachusetts!!Mean income (dollars)!!Estimate": "mean_income"
})

df.head(20)

,race,Massachusetts!!Number!!Estimate,Massachusetts!!Number!!Margin of Error,Massachusetts!!Percent Distribution!!Estimate,Massachusetts!!Percent Distribution!!Margin of Error,Massachusetts!!Mean income (dollars)!!Estimate,Massachusetts!!Mean income (dollars)!!Margin of Error,number,"Boston city, Massachusetts!!Number!!Margin of Error","Boston city, Massachusetts!!Percent Distribution!!Estimate","Boston city, Massachusetts!!Percent Distribution!!Margin of Error",mean_income,"Boston city, Massachusetts!!Mean income (dollars)!!Margin of Error"
0,HOUSEHOLD INCOME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,All households,"2,829,804","9,140","2,829,804","9,140","144,312","1,304","294,977","3,333","294,977","3,333","138,724","5,206"
2,With earnings,"2,226,456","11,252",78.70%,0.3,"149,436","1,513","238,679","5,436",80.90%,1.4,"147,632","4,750"
3,With wages or salary income,"2,160,543","12,511",76.30%,0.4,"146,494","1,441","234,329","5,448",79.40%,1.5,"145,324","4,915"
4,With self-employment income,"310,653","9,386",11.00%,0.3,"52,170","3,270","27,637","2,832",9.40%,1,"42,809","12,737"
5,"With interest, dividends, or net renta...","725,865","13,198",25.70%,0.5,"32,557","2,251","71,037","4,722",24.10%,1.5,"36,528","10,365"
6,With Social Security income,"872,672","10,854",30.80%,0.4,"25,232",325,"63,049","3,320",21.40%,1.1,"21,709","1,387"
7,With Supplemental Security Income (SSI),"151,041","6,430",5.30%,0.2,"10,918",348,"20,624","3,177",7.00%,1.1,"10,561",768
8,With cash public assistance income or ...,"454,353","10,564",16.10%,0.4,(X),(X),"65,125","3,882",22.10%,1.3,(X),(X)
9,With cash public assistance,"95,822","5,743",3.40%,0.2,"4,294",300,"12,078","2,060",4.10%,0.7,"4,057",761
10,With retirement income,"669,715","11,545",23.70%,0.4,"36,493","1,258","42,204","3,351",14.30%,1.1,"29,753","2,896"
11,With other types of income,"219,633","7,679",7.80%,0.3,"15,991",767,"15,894","2,481",5.40%,0.8,"12,437","2,131"
12,FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,All families,"1,761,366","13,364","1,761,366","13,364","174,000","1,658","130,183","5,138","130,183","5,138","165,069","10,433"
14,No workers,"224,175","8,094",12.70%,0.5,"87,875","4,196","16,263","1,962",12.50%,1.6,"66,425","22,918"
15,1 worker,"471,776","10,336",26.80%,0.6,"127,573","4,182","39,338","4,118",30.20%,2.8,"124,452","27,512"
16,"2 workers, both spouses worked","581,201","10,291",33.00%,0.5,"230,694","3,605","38,018","3,482",29.20%,2.3,"258,072","17,673"
17,"2 workers, other","206,666","8,709",11.70%,0.5,"139,954","4,948","19,723","2,608",15.20%,2,"132,882","16,802"
18,"3 or more workers, both spouses worked","198,427","7,923",11.30%,0.4,"250,850","6,348","9,461","1,810",7.30%,1.3,"205,289","29,582"
19,"3 or more workers, other","79,121","5,818",4.50%,0.3,"174,588","9,002","7,380","1,882",5.70%,1.4,"154,300","19,339"

In [6]:
df["race"] = df["race"].astype(str).str.strip()

df[["race", "number", "mean_income"]].head(20)

                                                 race   number mean_income
0                                    HOUSEHOLD INCOME      NaN         NaN
1                                      All households  294,977     138,724
2                                       With earnings  238,679     147,632
3                         With wages or salary income  234,329     145,324
4                         With self-employment income   27,637      42,809
5      With interest, dividends, or net rental income   71,037      36,528
6                         With Social Security income   63,049      21,709
7             With Supplemental Security Income (SSI)   20,624      10,561
8   With cash public assistance income or Food Sta...   65,125         (X)
9                         With cash public assistance   12,078       4,057
10                             With retirement income   42,204      29,753
11                         With other types of income   15,894      12,437
12       FAMILY INCOME BY NUMBER OF WORKERS IN FAMILY      NaN         NaN
13                                       All families  130,183     165,069
14                                         No workers   16,263      66,425
15                                           1 worker   39,338     124,452
16                     2 workers, both spouses worked   38,018     258,072
17                                   2 workers, other   19,723     132,882
18             3 or more workers, both spouses worked    9,461     205,289
19                           3 or more workers, other    7,380     154,300

In [7]:
# Find the row index where each section starts
one_race_start = df[df["race"].str.lower() == "one race"].index[0]
two_race_start = df[df["race"].str.lower() == "two or more races"].index[0]

# One race section = after "One race" until before "Two or more races"
one_race_df = df.loc[one_race_start + 1 : two_race_start - 1].copy()

# Two or more races section = after "Two or more races"
two_or_more_df = df.loc[two_race_start + 1 :].copy()

# Combine them
race_income = pd.concat([one_race_df, two_or_more_df], ignore_index=True)

race_income.head()

,race,Massachusetts!!Number!!Estimate,Massachusetts!!Number!!Margin of Error,Massachusetts!!Percent Distribution!!Estimate,Massachusetts!!Percent Distribution!!Margin of Error,Massachusetts!!Mean income (dollars)!!Estimate,Massachusetts!!Mean income (dollars)!!Margin of Error,number,"Boston city, Massachusetts!!Number!!Margin of Error","Boston city, Massachusetts!!Percent Distribution!!Estimate","Boston city, Massachusetts!!Percent Distribution!!Margin of Error",mean_income,"Boston city, Massachusetts!!Mean income (dollars)!!Margin of Error"
0,White,"4,761,129","19,095",66.70%,0.3,"65,979",687,"310,697","6,099",46.10%,0.9,"87,062","3,816"
1,Black or African American,"489,490","13,494",6.90%,0.2,"36,888","1,518","131,495","7,270",19.50%,1.1,"32,877","2,912"
2,American Indian and Alaska Native,"17,332","4,054",0.20%,0.1,"32,406","7,663","2,603","1,114",0.40%,0.2,"34,728","10,944"
3,Asian,"551,579","6,516",7.70%,0.1,"65,775","2,526","72,846","3,171",10.80%,0.5,"56,452","8,804"
4,Native Hawaiian and Other Pacific Islander,"1,265",458,0.00%,0.1,"48,410","31,863",106,144,0.00%,0.1,N,N

In [8]:
race_income = race_income[["race", "number", "mean_income"]].copy()

race_income.head(20)

                                         race   number mean_income
0                                       White  310,697      87,062
1                   Black or African American  131,495      32,877
2           American Indian and Alaska Native    2,603      34,728
3                                       Asian   72,846      56,452
4  Native Hawaiian and Other Pacific Islander      106           N
5                             Some other race   42,569      28,618
6     Hispanic or Latino origin (of any race)  139,222      31,632
7         White alone, not Hispanic or Latino  297,111      89,252

In [9]:
race_income = race_income[
    ~race_income["race"].str.lower().isin([
        "total",
        "one race",
        "two or more races",
        "race alone or in combination with one or more other races"
    ])
]

race_income = race_income.dropna(subset=["race"])

race_income

                                         race   number mean_income
0                                       White  310,697      87,062
1                   Black or African American  131,495      32,877
2           American Indian and Alaska Native    2,603      34,728
3                                       Asian   72,846      56,452
4  Native Hawaiian and Other Pacific Islander      106           N
5                             Some other race   42,569      28,618
6     Hispanic or Latino origin (of any race)  139,222      31,632
7         White alone, not Hispanic or Latino  297,111      89,252

In [11]:
race_income["number"] = (
    race_income["number"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("$", "", regex=False)
)

race_income["mean_income"] = (
    race_income["mean_income"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace("$", "", regex=False)
)

race_income["number"] = pd.to_numeric(race_income["number"], errors="coerce")
race_income["mean_income"] = pd.to_numeric(race_income["mean_income"], errors="coerce")

race_income = race_income.dropna(subset=["number", "mean_income"])

race_income

                                      race  number  mean_income
0                                    White  310697      87062.0
1                Black or African American  131495      32877.0
2        American Indian and Alaska Native    2603      34728.0
3                                    Asian   72846      56452.0
5                          Some other race   42569      28618.0
6  Hispanic or Latino origin (of any race)  139222      31632.0
7      White alone, not Hispanic or Latino  297111      89252.0